name: mrmt3
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - ffmpeg
  - tensorflow
  - pytorch
  - pip<24.1
  - protobuf<=3.20.3
  - pip:
    - transformers==4.21.3
    - librosa
    - t5
    - note-seq
    - pretty-midi
    - einops
    - ddsp
    - tensorflow-text
    - numpy
    - hydra-core
    - typing_extensions
    - torchaudio
    - tensorflow_probability
    - sentencepiece
    - pytorch_lightning
    - mir_eval
