name: mrmt3
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - ffmpeg
  - pip
  - pip:
    - transformers
    - torch
    - librosa
    - t5
    - note-seq
    - pretty-midi
    - einops
    - ddsp
    - tensorflow==2.19.0
    - tensorflow-text
    - protobuf
    - numpy
    - hydra-core
    - typing_extensions
    - torchaudio
    - tensorflow_probability
    - sentencepiece
    - pytorch_lightning
